name: Temperature Collector (Node.js)

on:
  workflow_dispatch:        # 내가 원할 때 버튼 눌러서 실행하겠다
  push:
    branches: [ main ]      # 코드 수정해서 올릴 때도 실행해라

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install @tuya/tuya-connector-nodejs firebase-admin

      - name: Run collector
        run: node test.js
 
